export const PRESETS = [
  {
    id: "cataract_surgery",
    label: "Cataract Surgery",
    description: "Typical post-op regimen with an antibiotic, a tapering steroid, and artificial tears.",
    medications: [
      {
        name: "Antibiotic (e.g. Vigamox)",
        bottle_cap_color: "blue",
        eye: "both",
        frequency_type: "four_daily",
        dose_times: ["07:00", "11:00", "15:00", "19:00"],
        start_date: null,
        end_date: null,
        ongoing: false,
        category: "antibiotic",
        instructions: { shake: false, refrigerate: false, wait_5_min: true, remove_contacts: false, press_tear_duct: true },
        taper_steps: [],
      },
      {
        name: "Steroid (e.g. Pred Forte)",
        bottle_cap_color: "pink",
        eye: "both",
        frequency_type: "four_daily",
        dose_times: ["07:00", "11:00", "15:00", "19:00"],
        start_date: null,
        end_date: null,
        ongoing: false,
        category: "steroid",
        instructions: { shake: true, refrigerate: false, wait_5_min: true, remove_contacts: false, press_tear_duct: true },
        taper_steps: [
          { start_date: null, frequency_type: "four_daily", dose_times: ["07:00", "11:00", "15:00", "19:00"] },
          { start_date: null, frequency_type: "three_daily", dose_times: ["08:00", "14:00", "20:00"] },
          { start_date: null, frequency_type: "twice_daily", dose_times: ["09:00", "21:00"] },
          { start_date: null, frequency_type: "once_daily", dose_times: ["09:00"] },
        ],
      },
      {
        name: "Artificial Tears",
        bottle_cap_color: "white",
        eye: "both",
        frequency_type: "custom_times",
        dose_times: ["09:00", "13:00", "17:00", "21:00"],
        start_date: null,
        end_date: null,
        ongoing: true,
        category: "artificial_tears",
        instructions: { shake: false, refrigerate: false, wait_5_min: false, remove_contacts: true, press_tear_duct: false },
        taper_steps: [],
      },
    ],
  },
];